### PR TITLE
Add OPM system

### PR DESCRIPTION
**Pull request by theastrogoth**
Add the info for the Outer Planet's Mod bodies.

I've also tweaked the initial position of the camera to give a "bird's eye view" of the solar system rather than looking on from the side.

Note: adding some additional planet packs may be tedious due to the lack of an `epoch` parameter for your orbits, which assume a reference time of t=0 (i.e. meanAnomaly0 occurs when the date is equal to zero). Some planet packs (OPM, RSS) have defined their planets' orbits with a nonzero epoch, which makes it necessary to "translate" them for your app by recalculating the meanAnomaly0 for an epoch of zero.

### CODE REVIEW

**Comment by nmisyats** [comment]
Thanks for the contribution !
I'll add that `epoch` paramter, I indeed never thought of that possibility ^^'. Is it a per system or a per body parameter ?
I guess the `meanAnomaly0` values in `opm/bodies.yml` are the manually translated ones ?
Maybe it'd better to wait a bit until I implement that and then make another pull request that uses the actual epoch(s) of OPM, for floating point precision purpose (if that has any effect ?).

There is also a problem in the `opm/bodies.yml` which is that some bodies are lacking data, for example (line 487) :
```yaml
- !!map
  id:                 23
  name:               Polta
  radius:             
  mass:               
  stdGravParam:       
  soi:                
  orbit:
    semiMajorAxis:    
    apoapsis:         
    periapsis:        
    eccentricity:     
    inclination:      
    argOfPeriapsis:   
    ascNodeLongitude: 
    sideralPeriod:    
  meanAnomaly0:       
  orbiting:           22
  color:  
```

Is it intentional ? It doesn't cause any problem at first (the bodies with no data are simply not rendered), but if you try to compute a trajectory which includes one of these it will throw an error. So this either need to be fixed, or comment the incomplete bodies so they are fully ignored (but that requires changing ids of the complete bodies after these ones).

**Comment by theastrogoth** [comment]
The `epoch` is a per-body parameter. I'm not sure why modders would do it, but they seem to sometimes give different bodies slightly different epochs (see [here](https://github.com/Poodmund/Outer-Planets-Mod/blob/master/GameData/OPM/KopernicusConfigs/SarnusMoons/Slate.cfg) and [here](https://github.com/Poodmund/Outer-Planets-Mod/blob/master/GameData/OPM/KopernicusConfigs/SarnusMoons/Tekto.cfg) for a couple of OPM bodies (search for "epoch")).

> There is also a problem in the opm/bodies.yml which is that some bodies are lacking data, for example (line 487) 

Oops! I think I must have some unstaged changes. I'll make sure all of the bodies are filled in when I'm back on my personal machine and I get the chance.

**Comment by nmisyats** [comment]
I added an `epoch` parameter in the `bodies.yml` files.

I think it'd be better to make a script that converts .cfg files of bodies into .yml files... because I noticed that you can put either degrees or radians for `meanAnomalyAtEpoch` in the .cfg, and my format requires radians only ^^'
That would help a lot and avoid having to manually add new parameters if ever needed.
I also noticed that the JNSQ data are wrong because the `meanAnomaly0` values have mixes of radians and degrees! So I must fix that too haha...

I'll try to work on that converter tool, but I have no idea when I will have it available.

Be sure all the values in OPM's `bodies.yml` are in the correct units and as precise as possible before I merge it.
Let me know as soon as you get all fixed.

**Comment by theastrogoth** [comment]
> I'll try to work on that converter tool, but I have no idea when I will have it available.

Just FYI, I have written some code to parse Kopernicus .cfg files, which you might find helpful if you want to do this. If you're curious, take a look at [`parseConfigNodes()`](https://github.com/theastrogoth/Kerbal-Transfer-Illustrator/blob/main/src/main/utilities/parseConfigNodes.ts) and [`fileToBodyConfig()`](https://github.com/theastrogoth/Kerbal-Transfer-Illustrator/blob/main/src/main/utilities/loadPlanetConfig.ts)

> Be sure all the values in OPM's bodies.yml are in the correct units and as precise as possible before I merge it.
Let me know as soon as you get all fixed.

Will do! Sorry I didn't have everything ready before opening the PR.

**Comment by theastrogoth** [comment]
Leaving a comment here to document the fact that this PR was not *actually* merged, but was closed when I brought my branch up to date with the upstream repo.

**Pull request merged**
